authorName: default
experimentName: bert
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 36
trainingServicePlatform: local
# specify your search space file
searchSpacePath: search_space.json
useAnnotation: false
advisor:
  #choice: BOHB; Hyperband
  builtinAdvisorName: BOHB
  classArgs:
    optimize_mode: minimize
trial:
  # file position in your docker container
  command: python3 bert_executor_hypertunining_nni.py
  codeDir: .
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu:  2
