authorName: default
experimentName: bert_adl
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 36
# specify your host ip
nniManagerIp: 10.20.41.120
trainingServicePlatform: adl
# specify your search space file
searchSpacePath: search_space.json
useAnnotation: false
advisor:
  #choice: BOHB; Hyperband
  builtinAdvisorName: BOHB
  classArgs:
    optimize_mode: minimize
trial:
  # file position in your docker container
  command: python3 /root/hypertuning/bert_executor_hypertunining_nni.py
  codeDir: .
  gpuNum: 1
  # docker image name
  image: registry.petuum.com/dev/nni:tmp-test-texar
  imagePullSecrets:
    - name: stagingsecret
  checkpoint:
    storageClass: aws-efs
    storageSize: 1Gi
